Pet component
Osttik/zoohope pull request #30
Opened 2024-03-03 10:56 UTC by 0y-a0

Did Pet page

2024-03-03 12:46 UTC, SergioVed commented on zoo-hope/src/styles/PetPage/Petpage.scss
> +.App{
Fix format

2024-03-03 12:49 UTC, SergioVed commented on zoo-hope/src/styles/PetPage/Petpage.scss
> +    color: rgba(35, 31, 32, 1);
Move twice or more used colours to variables

2024-03-03 13:12 UTC, SergioVed requested changes

2024-03-03 13:12 UTC, SergioVed commented on zoo-hope/src/components/PetPage/Pet.tsx
> +                <div className="secondBegBlock">
move to another component to reduce code complexity

2024-03-03 13:12 UTC, SergioVed commented on zoo-hope/src/components/PetPage/Pet.tsx
> +            <div className="extraPetsBlock">
move to another component to reduce code complexity

2024-03-06 10:52 UTC, Osttik requested changes

2024-03-06 10:52 UTC, Osttik commented on zoo-hope/src/components/PetPage/FirstPetBlock.tsx
> +export function First_Pet_Block(){
Lets have better namings
Like this could be 'PetInfo'

2024-03-06 10:52 UTC, Osttik commented on zoo-hope/src/components/PetPage/FourthPetBlock.tsx
> +export function Fourth_Pet_Block(){
This 'OtherPets'

2024-03-06 10:52 UTC, Osttik commented on zoo-hope/src/components/PetPage/NdPetBlock.tsx
> +export function Second_Pet_Block(){
This 'PetStory'

2024-03-06 10:52 UTC, Osttik commented on zoo-hope/src/components/PetPage/RdPetBlock.tsx
> +export function Third_Pet_Block(){
And this, 'HelpPet'

2024-03-06 15:21 UTC, merged